-keep class com.origin.commons.callerid.helpers.** { *; }
-keep class com.origin.commons.callerid.model.** { *; }
-keep class com.origin.commons.callerid.ads.** { *; }
-keep class com.origin.commons.callerid.db.** { *; }
-keep class com.origin.commons.callerid.db.entity.** { *; }